upload_max_filesize = 15M
post_max_size = 15M
short_open_tags = On
error_log = "/var/log/php/error.log"
error_reporting = E_ALL ^ E_DEPRECATED ^ E_WARNING
log_errors = On

[xdebug]
zend_extension=xdebug.so
xdebug.mode=debug
xdebug.start_with_request=yes
xdebug.client_host=host.docker.internal
xdebug.client_port=9003
xdebug.log=/var/log/php/xdebug.log
xdebug.log_level=7
xdebug.idekey=PHPSTORM